"""add admin role tables

Revision ID: 01c81752b58b
Revises: cba7deed855b
Create Date: 2026-08-15 06:24:21.046405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c81752b58b'
down_revision: Union[str, None] = 'cba7deed855b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SECURITY_QUESTIONS_TABLE = sa.table(
    'security_questions',
    sa.column('id', sa.Integer),
    sa.column('question_text', sa.String),
    sa.column('display_order', sa.SmallInteger),
)

PLACEHOLDER_SECURITY_QUESTIONS = [
    "PLACEHOLDER: What was the name of your first pet?",
    "PLACEHOLDER: What city were you born in?",
    "PLACEHOLDER: What was your childhood best friend's name?",
    "PLACEHOLDER: What was the make of your first car?",
    "PLACEHOLDER: What is your mother's maiden name?",
]


def upgrade() -> None:
    # Widen the role CHECK constraint to add 'admin' — autogenerate doesn't
    # detect CHECK constraint text changes, so this is hand-added.
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.create_check_constraint('ck_users_role', 'users', "role IN ('coordinator', 'student', 'admin')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_text')
    )
    op.bulk_insert(
        SECURITY_QUESTIONS_TABLE,
        [
            {'id': i, 'question_text': text, 'display_order': i}
            for i, text in enumerate(PLACEHOLDER_SECURITY_QUESTIONS, start=1)
        ],
    )
    # bulk_insert with explicit ids doesn't advance the identity sequence —
    # the next real INSERT would collide with id=1 otherwise.
    op.execute(
        "SELECT setval(pg_get_serial_sequence('security_questions', 'id'), "
        "(SELECT MAX(id) FROM security_questions))"
    )
    op.create_table('admin_reset_challenges',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('security_question_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_question_id'], ['security_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('admin_security_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('security_question_id', sa.Integer(), nullable=False),
    sa.Column('hashed_answer', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_question_id'], ['security_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'security_question_id', name='uq_admin_security_answer')
    )
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='SENT', nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SENT', 'FAILED')", name='ck_email_log_status'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requested_role IN ('coordinator', 'student')", name='ck_password_reset_requests_role'),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name='ck_password_reset_requests_status'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_password_reset_requests_pending_user', 'password_reset_requests', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('signup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('requested_batch_id', sa.Integer(), nullable=False),
    sa.Column('monthly_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('resulting_student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name='ck_signup_requests_status'),
    sa.ForeignKeyConstraint(['requested_batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['resulting_student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_signup_requests_pending_email', 'signup_requests', ['email'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_signup_requests_pending_email', table_name='signup_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('signup_requests')
    op.drop_index('uq_password_reset_requests_pending_user', table_name='password_reset_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('password_reset_requests')
    op.drop_table('email_log')
    op.drop_table('admin_security_answers')
    op.drop_table('admin_reset_challenges')
    op.drop_table('security_questions')
    # ### end Alembic commands ###

    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.create_check_constraint('ck_users_role', 'users', "role IN ('coordinator', 'student')")
